### ISSUE TITLE
chooseFileButton's <YourChooseButton /> can't show

### ISSUE THREAD

**Issue by jingxinxin** [wubocong/react-upload-file#1]
>  <ReactUploadFile options={uploadFileOptions}
                               chooseFileButton={\<Button>f\</Button>}
                               uploadFileButton={\<Button color='green'
                                                         content='上传'
                                                         icon="upload"/>}/>
\<Button>f\</Button> can't show . Button is myself component

**Comment by wubocong** [comment]
@jingxinxin Can you give me the full content of this file for debug, thx!

**Comment by v-zaburdaev** [comment]
I have a same problem. The childs of <Button></Button> replaced by hidden <input> element
<input type="file" name="ajax-upload-file-input" accept="image/*" multiple="" style="display: none;">

It needs to create special class for right rendering child and catch onClick event. My example:
import React from "react";
import {Button} from "react-bootstrap";

```
class UploadButton extends React.Component {
    constructor(props) {
        super(props);
    }
    onclick(e){
        this.props.onClick(e);
    }
    render(){
        return <Button onClick={this.onclick.bind(this)}>Upload files
          **{this.props.children}**</Button>;
    }
}

UploadButton.propTypes = {
    children: React.PropTypes.array.isRequired,
    onClick: React.PropTypes.func.isRequired
};

export default UploadButton;
```

You can read childs of chooseFileButton element and add <input> element to his childrens.

**Comment by slxiao** [comment]
@jingxinxin  I met the same issue

**Comment by vstlouis** [comment]
You need to return <button> and not <Button> from this component.

**Comment by wubocong** [comment]
@v-zaburdaev You are right, i will improve this.
